### ISSUE TITLE
fluxbox

### ISSUE THREAD

**Issue by xenoterracide** [johanmalm/labwc#12]
I used openbox, blackbox, and fluxbox, way back >15 years ago. I switched largely because I thought mounting removable media was a pain. Of the 3, I thought fluxbox was the best, I don't remember if it's how the right click menus worked, I think it had tabbed windows, and you could easily trigger a run prompt. I know it had a taskbar. It was still of course very minimal. Do you have any plans to investigate its features to make certain they're available?

**Comment by johanmalm** [comment]
Sorry, missed this one.
I have used both openbox and fluxbox.
I decided to use openbox spec (a) in order to avoid re-inventing a spec; (b) because it's pretty 'no-frills' and (c) because I think it's widely adopted (e.g. by LXDE, raspberry pi, Bunsenlabs, etc).
I do quite like the fluxbox menu syntax, but think it's simpler to just stick with the openbox xml format.
Regarding run-prompts, taskbars and the like, I intend to use other applications for this.
The aim is to keep the code base pretty small+simple and just focus on being a good stacking window compositor (albeit with a menu :smile:)
