### ISSUE TITLE
Unable to drag windows

### ISSUE THREAD

**Issue by joeftiger** [johanmalm/labwc#34]
Hello

I am trying out `labwc` to keep a wm that resembles openbox from xorg.

I have some issues that may stem from bad configs perhaps. I reconfigured/restarted labwc several times.

## Some files
<details>
<summary><code>rc.xml</code></summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Use <openbox_config> as root element for openbox compatibility -->
<openbox_config>

<!-- labwc specific settings - additional to openbox -->
<lab>
  <!-- Use server-side decorations for xdg-shell views if CSD can be disabled -->
  <xdg_shell_server_side_deco>yes</xdg_shell_server_side_deco>
</lab>

<theme>
  <!-- <name>Clearlooks-3.4</name> -->
  <!-- This font size also determintes the height of the window title bar -->
  <font place="ActiveWindow">
    <name>JetBrains Mono</name>
    <size>10</size>
  </font>
</theme>

<!-- see labwc-actions(5) for a list of supported actions -->
<keyboard>
  <keybind key="A-Escape">
    <action name="Exit"/>
  </keybind>
  <keybind key="A-Tab">
    <action name="NextWindow"/>
  </keybind>
  <keybind key="S-T">
    <action name="Execute"><command>alacritty</command></action>
  </keybind>
</keyboard>

<mouse>
  <context name="Frame">
    <mousebind button="A-Left" action="Drag">
      <action name="Move"/>
    </mousebind>
    <mousebind button="A-Right" action="Drag">
      <action name="Resize"/>
    </mousebind>
  </context>
</mouse>
</openbox_config>
```
</details>

<details>
<summary>Simple <code>labwc</code> startup log</summary>

```
[labwc] info: read environment file (/home/julius/.config/labwc/environment)
[labwc] info: read config file (/home/julius/.config/labwc/rc.xml)
[labwc] info: tap enabled for libinput device
[labwc] info: cannot find theme (Clearlooks-3.4), using built-in
[labwc] info: read menu file (/home/julius/.config/labwc/menu.xml)
[labwc] info: run autostart file (/home/julius/.config/labwc/autostart)
```
</details>

## My issues
1. Trying to open `alacritty` (terminal) with `Super-T` does nothing, I have to open it manually from the `menu.xml`.
2. Trying to open `telegram-desktop` from both `menu.xml` and `alacritty` results in a segfault.
3. Trying to `move` or `resize` the windows does nothing.
4. Trying to switch to `tty1` or any other does not work. Do I need to add a keybind?
4. The above log mentions 
    > [labwc] info: cannot find theme (Clearlooks-3.4), using built-in

   Where would I get this theme from?

**Comment by johanmalm** [comment]
Not sure.
First of all. What distro are you using? Are you running directly from a tty or under X11?
Suggest we start with points (1) and (3).

Point 3. Very strange. Do you get the same if you remove all your config files. Are using more than one screen? Can you click one windows to focus them? Is the menu working as expected? Does the cursor image change when hovering over window edges?

Point 1. Could you try with Alt rather than Super? If running under X11 it might be the X window manager interfering.

**Comment by johanmalm** [comment]
Point 1. Could you try `<keybind key="W-t">` instead?

Point 3. Are you sure you're not maximized? Try clicking the maximize/unmaximize button to see if the allows you to resize/move.

**Comment by joeftiger** [comment]
Ohhhhh, it could well be that `W-xyz` was the problem as I used `S`. Apparently it's shift instead of super key. 

> First of all. What distro are you using? Are you running directly from a tty or under X11?

I started it from tty, barebones Arch Linux where I used weston until now.

**Comment by joeftiger** [comment]
@johanmalm I switched to `<keybind key="W-t">` and I can open alacritty now. 

Dragging still does not work however. I tried Super and Alt. I can only drag with the default mechanism when pressing left click on the header decoration. 

I further noticed that I can't move my browser window (`brave`) at all, it has it's own decorations though, might be because of that in conjunction with above bug.

**Comment by johanmalm** [comment]
1. Resolved. Just use W-t
2. Qt applications can now run in wayland mode without segfault. Fixed in https://github.com/johanmalm/labwc/commit/be27bb30a3f7a856ce95f023fc0ffa0120864422
3. For the time being you just have to drag title bar or edges. We will support other methods, but want to focus on fundamentals first.
4. We now catch ctrl+alt+F1 to F12 to change virtual terminal. Fixed in https://github.com/johanmalm/labwc/commit/5f0c2d75b5b1e3fdb1e9f6368b19741e894a71f0
5. We don't revert to Clearlooks-3.4 anymore. However, there are lots of openbox themes on the internet - just search. For clearlooks-3.4, just install openbox and you'll get it automatically.

Appreciate your feedback. Will close now, but shout if there are other problems. For separate issues, please open a new issue.
